/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif



#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "SDFCryptoProvider.h"


#include <string>


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_SM2_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  dev::crypto::AlgorithmType result;
  
  (void)jenv;
  (void)jcls;
  result = (dev::crypto::AlgorithmType)dev::crypto::SM2;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_SM3_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  dev::crypto::AlgorithmType result;
  
  (void)jenv;
  (void)jcls;
  result = (dev::crypto::AlgorithmType)dev::crypto::SM3;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_SM4_1CBC_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  dev::crypto::AlgorithmType result;
  
  (void)jenv;
  (void)jcls;
  result = (dev::crypto::AlgorithmType)dev::crypto::SM4_CBC;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_Key_1PublicKey(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  dev::crypto::Key *arg1 = (dev::crypto::Key *) 0 ;
  unsigned char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::Key **)&jarg1; 
  result = (unsigned char *)((dev::crypto::Key const *)arg1)->PublicKey();
  *(unsigned char **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_Key_1PrivateKey(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  dev::crypto::Key *arg1 = (dev::crypto::Key *) 0 ;
  unsigned char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::Key **)&jarg1; 
  result = (unsigned char *)((dev::crypto::Key const *)arg1)->PrivateKey();
  *(unsigned char **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_Key_1PublicKeyLen(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  dev::crypto::Key *arg1 = (dev::crypto::Key *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::Key **)&jarg1; 
  result = (int)((dev::crypto::Key const *)arg1)->PublicKeyLen();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_Key_1PrivateKeyLen(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  dev::crypto::Key *arg1 = (dev::crypto::Key *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::Key **)&jarg1; 
  result = (int)((dev::crypto::Key const *)arg1)->PrivateKeyLen();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_Key_1Identifier(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  dev::crypto::Key *arg1 = (dev::crypto::Key *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::Key **)&jarg1; 
  result = (unsigned int)((dev::crypto::Key const *)arg1)->Identifier();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_Key_1Password(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  dev::crypto::Key *arg1 = (dev::crypto::Key *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::Key **)&jarg1; 
  result = (char *)((dev::crypto::Key const *)arg1)->Password();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_Key_1IsInternalKey(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  dev::crypto::Key *arg1 = (dev::crypto::Key *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::Key **)&jarg1; 
  result = (bool)((dev::crypto::Key const *)arg1)->IsInternalKey();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_new_1Key_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  dev::crypto::Key *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (dev::crypto::Key *)new dev::crypto::Key();
  *(dev::crypto::Key **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_new_1Key_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jint jarg4) {
  jlong jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  int arg2 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  int arg4 ;
  dev::crypto::Key *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(unsigned char **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(unsigned char **)&jarg3; 
  arg4 = (int)jarg4; 
  result = (dev::crypto::Key *)new dev::crypto::Key(arg1,arg2,arg3,arg4);
  *(dev::crypto::Key **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_new_1Key_1_1SWIG_12(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  unsigned int arg1 ;
  char **arg2 = 0 ;
  char *temp2 = 0 ;
  dev::crypto::Key *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  arg2 = 0;
  if (jarg2) {
    temp2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!temp2) return 0;
  }
  arg2 = &temp2;
  result = (dev::crypto::Key *)new dev::crypto::Key(arg1,*arg2);
  *(dev::crypto::Key **)&jresult = result; 
  if (arg2 && *arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)*arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_new_1Key_1_1SWIG_13(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  unsigned int arg1 ;
  dev::crypto::Key *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  result = (dev::crypto::Key *)new dev::crypto::Key(arg1);
  *(dev::crypto::Key **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_Key_1setPrivateKey(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  dev::crypto::Key *arg1 = (dev::crypto::Key *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::Key **)&jarg1; 
  arg2 = *(unsigned char **)&jarg2; 
  arg3 = (unsigned int)jarg3; 
  (arg1)->setPrivateKey(arg2,arg3);
}


SWIGEXPORT void JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_Key_1setPublicKey(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  dev::crypto::Key *arg1 = (dev::crypto::Key *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::Key **)&jarg1; 
  arg2 = *(unsigned char **)&jarg2; 
  arg3 = (unsigned int)jarg3; 
  (arg1)->setPublicKey(arg2,arg3);
}


SWIGEXPORT void JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_delete_1Key(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  dev::crypto::Key *arg1 = (dev::crypto::Key *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(dev::crypto::Key **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_SDFCryptoResult_1signature_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  dev::crypto::SDFCryptoResult *arg1 = (dev::crypto::SDFCryptoResult *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::SDFCryptoResult **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return ;
  }
  {
    delete [] arg1->signature;
    if (arg2) {
      arg1->signature = (char *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->signature, (const char *)arg2);
    } else {
      arg1->signature = 0;
    }
  }
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_SDFCryptoResult_1signature_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  dev::crypto::SDFCryptoResult *arg1 = (dev::crypto::SDFCryptoResult *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::SDFCryptoResult **)&jarg1; 
  result = (char *) ((arg1)->signature);
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_SDFCryptoResult_1publicKey_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  dev::crypto::SDFCryptoResult *arg1 = (dev::crypto::SDFCryptoResult *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::SDFCryptoResult **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return ;
  }
  {
    delete [] arg1->publicKey;
    if (arg2) {
      arg1->publicKey = (char *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->publicKey, (const char *)arg2);
    } else {
      arg1->publicKey = 0;
    }
  }
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_SDFCryptoResult_1publicKey_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  dev::crypto::SDFCryptoResult *arg1 = (dev::crypto::SDFCryptoResult *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::SDFCryptoResult **)&jarg1; 
  result = (char *) ((arg1)->publicKey);
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_SDFCryptoResult_1privateKey_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  dev::crypto::SDFCryptoResult *arg1 = (dev::crypto::SDFCryptoResult *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::SDFCryptoResult **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return ;
  }
  {
    delete [] arg1->privateKey;
    if (arg2) {
      arg1->privateKey = (char *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->privateKey, (const char *)arg2);
    } else {
      arg1->privateKey = 0;
    }
  }
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_SDFCryptoResult_1privateKey_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  dev::crypto::SDFCryptoResult *arg1 = (dev::crypto::SDFCryptoResult *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::SDFCryptoResult **)&jarg1; 
  result = (char *) ((arg1)->privateKey);
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_SDFCryptoResult_1result_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  dev::crypto::SDFCryptoResult *arg1 = (dev::crypto::SDFCryptoResult *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::SDFCryptoResult **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->result = arg2;
}


SWIGEXPORT jboolean JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_SDFCryptoResult_1result_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  dev::crypto::SDFCryptoResult *arg1 = (dev::crypto::SDFCryptoResult *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::SDFCryptoResult **)&jarg1; 
  result = (bool) ((arg1)->result);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_SDFCryptoResult_1hash_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  dev::crypto::SDFCryptoResult *arg1 = (dev::crypto::SDFCryptoResult *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::SDFCryptoResult **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return ;
  }
  {
    delete [] arg1->hash;
    if (arg2) {
      arg1->hash = (char *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->hash, (const char *)arg2);
    } else {
      arg1->hash = 0;
    }
  }
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_SDFCryptoResult_1hash_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  dev::crypto::SDFCryptoResult *arg1 = (dev::crypto::SDFCryptoResult *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::SDFCryptoResult **)&jarg1; 
  result = (char *) ((arg1)->hash);
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_SDFCryptoResult_1sdfErrorMessage_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  dev::crypto::SDFCryptoResult *arg1 = (dev::crypto::SDFCryptoResult *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::SDFCryptoResult **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return ;
  }
  {
    delete [] arg1->sdfErrorMessage;
    if (arg2) {
      arg1->sdfErrorMessage = (char *) (new char[strlen((const char *)arg2)+1]);
      strcpy((char *)arg1->sdfErrorMessage, (const char *)arg2);
    } else {
      arg1->sdfErrorMessage = 0;
    }
  }
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_SDFCryptoResult_1sdfErrorMessage_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  dev::crypto::SDFCryptoResult *arg1 = (dev::crypto::SDFCryptoResult *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(dev::crypto::SDFCryptoResult **)&jarg1; 
  result = (char *) ((arg1)->sdfErrorMessage);
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_new_1SDFCryptoResult(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  dev::crypto::SDFCryptoResult *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (dev::crypto::SDFCryptoResult *)new dev::crypto::SDFCryptoResult();
  *(dev::crypto::SDFCryptoResult **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_delete_1SDFCryptoResult(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  dev::crypto::SDFCryptoResult *arg1 = (dev::crypto::SDFCryptoResult *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(dev::crypto::SDFCryptoResult **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_KeyGen(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  dev::crypto::AlgorithmType arg1 ;
  dev::crypto::SDFCryptoResult result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (dev::crypto::AlgorithmType)jarg1; 
  result = dev::crypto::KeyGen(arg1);
  *(dev::crypto::SDFCryptoResult **)&jresult = new dev::crypto::SDFCryptoResult((const dev::crypto::SDFCryptoResult &)result); 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_Sign(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2, jstring jarg3) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  dev::crypto::AlgorithmType arg2 ;
  char *arg3 = (char *) 0 ;
  dev::crypto::SDFCryptoResult result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)jenv->GetStringUTFChars(jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (dev::crypto::AlgorithmType)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)jenv->GetStringUTFChars(jarg3, 0);
    if (!arg3) return 0;
  }
  result = dev::crypto::Sign(arg1,arg2,(char const *)arg3);
  *(dev::crypto::SDFCryptoResult **)&jresult = new dev::crypto::SDFCryptoResult((const dev::crypto::SDFCryptoResult &)result); 
  if (arg1) jenv->ReleaseStringUTFChars(jarg1, (const char *)arg1);
  if (arg3) jenv->ReleaseStringUTFChars(jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_SignWithInternalKey(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3, jstring jarg4) {
  jlong jresult = 0 ;
  unsigned int arg1 ;
  char *arg2 = (char *) 0 ;
  dev::crypto::AlgorithmType arg3 ;
  char *arg4 = (char *) 0 ;
  dev::crypto::SDFCryptoResult result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (dev::crypto::AlgorithmType)jarg3; 
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)jenv->GetStringUTFChars(jarg4, 0);
    if (!arg4) return 0;
  }
  result = dev::crypto::SignWithInternalKey(arg1,arg2,arg3,(char const *)arg4);
  *(dev::crypto::SDFCryptoResult **)&jresult = new dev::crypto::SDFCryptoResult((const dev::crypto::SDFCryptoResult &)result); 
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
  if (arg4) jenv->ReleaseStringUTFChars(jarg4, (const char *)arg4);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_Verify(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2, jstring jarg3, jstring jarg4) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  dev::crypto::AlgorithmType arg2 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  dev::crypto::SDFCryptoResult result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)jenv->GetStringUTFChars(jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (dev::crypto::AlgorithmType)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)jenv->GetStringUTFChars(jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)jenv->GetStringUTFChars(jarg4, 0);
    if (!arg4) return 0;
  }
  result = dev::crypto::Verify(arg1,arg2,(char const *)arg3,(char const *)arg4);
  *(dev::crypto::SDFCryptoResult **)&jresult = new dev::crypto::SDFCryptoResult((const dev::crypto::SDFCryptoResult &)result); 
  if (arg1) jenv->ReleaseStringUTFChars(jarg1, (const char *)arg1);
  if (arg3) jenv->ReleaseStringUTFChars(jarg3, (const char *)arg3);
  if (arg4) jenv->ReleaseStringUTFChars(jarg4, (const char *)arg4);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_VerifyWithInternalKey(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jstring jarg3, jstring jarg4) {
  jlong jresult = 0 ;
  unsigned int arg1 ;
  dev::crypto::AlgorithmType arg2 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  dev::crypto::SDFCryptoResult result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  arg2 = (dev::crypto::AlgorithmType)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)jenv->GetStringUTFChars(jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)jenv->GetStringUTFChars(jarg4, 0);
    if (!arg4) return 0;
  }
  result = dev::crypto::VerifyWithInternalKey(arg1,arg2,(char const *)arg3,(char const *)arg4);
  *(dev::crypto::SDFCryptoResult **)&jresult = new dev::crypto::SDFCryptoResult((const dev::crypto::SDFCryptoResult &)result); 
  if (arg3) jenv->ReleaseStringUTFChars(jarg3, (const char *)arg3);
  if (arg4) jenv->ReleaseStringUTFChars(jarg4, (const char *)arg4);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_Hash(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2, jstring jarg3) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  dev::crypto::AlgorithmType arg2 ;
  char *arg3 = (char *) 0 ;
  dev::crypto::SDFCryptoResult result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)jenv->GetStringUTFChars(jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (dev::crypto::AlgorithmType)jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)jenv->GetStringUTFChars(jarg3, 0);
    if (!arg3) return 0;
  }
  result = dev::crypto::Hash(arg1,arg2,(char const *)arg3);
  *(dev::crypto::SDFCryptoResult **)&jresult = new dev::crypto::SDFCryptoResult((const dev::crypto::SDFCryptoResult &)result); 
  if (arg1) jenv->ReleaseStringUTFChars(jarg1, (const char *)arg1);
  if (arg3) jenv->ReleaseStringUTFChars(jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_webank_wedpr_crypto_hsm_sdf_SDFJNI_ExportInternalPublicKey(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  unsigned int arg1 ;
  dev::crypto::AlgorithmType arg2 ;
  dev::crypto::SDFCryptoResult result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  arg2 = (dev::crypto::AlgorithmType)jarg2; 
  result = dev::crypto::ExportInternalPublicKey(arg1,arg2);
  *(dev::crypto::SDFCryptoResult **)&jresult = new dev::crypto::SDFCryptoResult((const dev::crypto::SDFCryptoResult &)result); 
  return jresult;
}


#ifdef __cplusplus
}
#endif

